package com.nexauren.drawmotion;

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.BlurMaskFilter;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Matrix;
import android.graphics.Paint;
import android.graphics.PorterDuff;
import android.graphics.PorterDuffXfermode;
import android.graphics.RectF;
import android.view.MotionEvent;
import android.view.View;
import android.widget.Toast;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

public class EditorCanvasView extends View {
    public static final int BRUSH=0,LINE=1,RECT=2,ELLIPSE=3,FILL=4,PICK=5,ERASE=6,MOVE=7;
    public static final int RULER_OFF=0,RULER_STRAIGHT=1,RULER_GRID=2,RULER_PERSPECTIVE=3,RULER_RADIAL=4;
    public static final String[] BRUSHES={"Ink","Pencil","Marker","Airbrush","Neon","Pixel","Chalk","Oil","Watercolor","Calligraphy","G-Pen","Glow"};
    public static final String[] RULERS={"Off","Straight","Grid","Perspective","Radial"};
    public static class FrameModel{public final ArrayList<LayerModel> layers=new ArrayList<>();FrameModel copy(){FrameModel f=new FrameModel();for(LayerModel l:layers)f.layers.add(l.copy());return f;}}
    private final Paint paint=new Paint(Paint.ANTI_ALIAS_FLAG|Paint.DITHER_FLAG),bitmapPaint=new Paint(Paint.ANTI_ALIAS_FLAG|Paint.FILTER_BITMAP_FLAG);
    private final ArrayDeque<Bitmap> undo=new ArrayDeque<>(),redo=new ArrayDeque<>();private final ArrayList<FrameModel> frames=new ArrayList<>();
    private int projectW=720,projectH=720,frame=0,layer=1,tool=BRUSH,brush=0,symmetry=0,ruler=RULER_OFF,fps=12;private int brushColor=Color.rgb(31,41,55);private float size=18f,sx,sy,lx,ly,moveStartX,moveStartY;private boolean animation=false,onion=true,grid=false,playing=false;private String projectName="Untitled";private Runnable playTask;private RectF canvasRect=new RectF();private float scale=1f;
    public EditorCanvasView(Context c){super(c);setLayerType(View.LAYER_TYPE_SOFTWARE,null);paint.setStrokeCap(Paint.Cap.ROUND);paint.setStrokeJoin(Paint.Join.ROUND);ensure();}
    public void setAnimationMode(boolean v){animation=v;ensure();invalidate();}public boolean isAnimationMode(){return animation;}public void setOnionSkin(boolean v){onion=v;invalidate();}public void setGrid(boolean v){grid=v;invalidate();}public void setRuler(int v){ruler=Math.max(0,Math.min(RULER_RADIAL,v));invalidate();}public int getRuler(){return ruler;}public void setSymmetry(int v){symmetry=Math.max(0,Math.min(4,v));invalidate();}public void setBrushColor(int v){brushColor=v;tool=BRUSH;}public void setBrushSize(float v){size=Math.max(1,Math.min(120,v));}public float getBrushSize(){return size;}public void setBrushPreset(int v){brush=Math.max(0,Math.min(BRUSHES.length-1,v));tool=BRUSH;invalidate();}public int getBrushPreset(){return brush;}public void setTool(int v){tool=v;invalidate();}public int getFrameCount(){return frames.size();}public int getCurrentFrame(){return frame;}public int getLayerIndex(){return layer;}public boolean isPlaying(){return playing;}public void setFps(int v){fps=Math.max(1,Math.min(30,v));}public int getFps(){return fps;}public void setProjectName(String v){if(v!=null&&!v.trim().isEmpty())projectName=v.trim();}public String getProjectName(){return projectName;}public List<FrameModel> getFrames(){return frames;}
    private void ensure(){if(frames.isEmpty()){FrameModel f=new FrameModel();f.layers.add(new LayerModel("Background",solid(Color.WHITE)));f.layers.get(0).locked=true;f.layers.add(new LayerModel("Artwork",blank()));frames.add(f);}if(frame>=frames.size())frame=Math.max(0,frames.size()-1);if(layer>=frames.get(frame).layers.size())layer=Math.max(0,frames.get(frame).layers.size()-1);}
    private Bitmap blank(){return Bitmap.createBitmap(projectW,projectH,Bitmap.Config.ARGB_8888);}private Bitmap solid(int c){Bitmap b=blank();b.eraseColor(c);return b;}private void recycle(Bitmap b){if(b!=null&&!b.isRecycled())b.recycle();}private void clearHistory(){while(!undo.isEmpty())recycle(undo.pop());while(!redo.isEmpty())recycle(redo.pop());}
    private void snapshot(){ensure();LayerModel l=frames.get(frame).layers.get(layer);if(l.locked)return;undo.push(l.bitmap.copy(Bitmap.Config.ARGB_8888,true));while(undo.size()>20)recycle(undo.removeLast());while(!redo.isEmpty())recycle(redo.pop());}
    public void undo(){if(undo.isEmpty())return;LayerModel l=frames.get(frame).layers.get(layer);redo.push(l.bitmap.copy(Bitmap.Config.ARGB_8888,true));recycle(l.bitmap);l.bitmap=undo.pop();invalidate();}public void redo(){if(redo.isEmpty())return;LayerModel l=frames.get(frame).layers.get(layer);undo.push(l.bitmap.copy(Bitmap.Config.ARGB_8888,true));recycle(l.bitmap);l.bitmap=redo.pop();invalidate();}
    public void addFrame(){ensure();FrameModel f=new FrameModel();for(LayerModel l:frames.get(frame).layers){LayerModel n=new LayerModel(l.name,blank());n.visible=l.visible;n.opacity=l.opacity;n.locked=l.locked;n.blendMode=l.blendMode;f.layers.add(n);}frames.add(frame+1,f);frame++;layer=Math.min(layer,f.layers.size()-1);clearHistory();invalidate();}
    public void duplicateFrame(){ensure();frames.add(frame+1,frames.get(frame).copy());frame++;clearHistory();invalidate();}public void deleteFrame(){if(!animation||frames.size()<2)return;FrameModel f=frames.remove(frame);freeFrame(f);frame=Math.min(frame,frames.size()-1);clearHistory();invalidate();}public void selectFrame(int x){if(x<0||x>=frames.size())return;frame=x;layer=Math.min(layer,frames.get(frame).layers.size()-1);clearHistory();invalidate();}
    public String[] layerNames(){ensure();String[] r=new String[frames.get(frame).layers.size()];for(int i=0;i<r.length;i++){LayerModel l=frames.get(frame).layers.get(i);r[i]=(i==layer?"● ":"")+l.name+(l.locked?" 🔒":"");}return r;}public void selectLayer(int x){ensure();if(x>=0&&x<frames.get(frame).layers.size()){layer=x;clearHistory();invalidate();}}public void addLayer(){ensure();LayerModel n=new LayerModel("Layer "+(frames.get(frame).layers.size()+1),blank());frames.get(frame).layers.add(layer+1,n);layer++;invalidate();}public void duplicateLayer(){ensure();LayerModel src=frames.get(frame).layers.get(layer);if(src.locked)return;LayerModel n=src.copy();n.name=src.name+" Copy";frames.get(frame).layers.add(layer+1,n);layer++;invalidate();}public void deleteLayer(){ensure();if(layer<=0||frames.get(frame).layers.size()<=2)return;LayerModel x=frames.get(frame).layers.remove(layer);recycle(x.bitmap);layer=Math.max(1,layer-1);invalidate();}public void moveLayerUp(){ensure();if(layer<frames.get(frame).layers.size()-1){LayerModel a=frames.get(frame).layers.remove(layer);frames.get(frame).layers.add(layer+1,a);layer++;invalidate();}}public void moveLayerDown(){ensure();if(layer>1){LayerModel a=frames.get(frame).layers.remove(layer);frames.get(frame).layers.add(layer-1,a);layer--;invalidate();}}public void toggleLayer(){frames.get(frame).layers.get(layer).visible=!frames.get(frame).layers.get(layer).visible;invalidate();}public void setLayerOpacity(int o){frames.get(frame).layers.get(layer).opacity=Math.max(0,Math.min(255,o));invalidate();}public void cycleBlend(){LayerModel l=frames.get(frame).layers.get(layer);l.blendMode=(l.blendMode+1)%5;invalidate();}public String currentLayerName(){return frames.get(frame).layers.get(layer).name;}public String currentBlend(){return LayerModel.blendName(frames.get(frame).layers.get(layer).blendMode);}
    @Override protected void onSizeChanged(int w,int h,int ow,int oh){super.onSizeChanged(w,h,ow,oh);updateRect();}private void updateRect(){float pad=16*getResources().getDisplayMetrics().density,maxW=Math.max(1,getWidth()-pad*2),maxH=Math.max(1,getHeight()-pad*2);scale=Math.min(maxW/projectW,maxH/projectH);float cw=projectW*scale,ch=projectH*scale;canvasRect.set((getWidth()-cw)/2f,(getHeight()-ch)/2f,(getWidth()+cw)/2f,(getHeight()+ch)/2f);}
    @Override protected void onDraw(Canvas c){ensure();updateRect();c.drawColor(Color.rgb(246,248,251));c.save();c.translate(canvasRect.left,canvasRect.top);c.scale(scale,scale);c.drawColor(Color.WHITE);drawOnion(c);drawFrame(c,frame,true);if(grid||ruler==RULER_GRID)drawGrid(c);drawRuler(c);c.restore();}
    private void drawFrame(Canvas c,int index,boolean bg){if(index<0||index>=frames.size())return;for(LayerModel l:frames.get(index).layers){if(!bg&&l.name.equals("Background"))continue;l.draw(c,bitmapPaint);}}private void drawOnion(Canvas c){if(!animation||!onion)return;if(frame>0){bitmapPaint.setAlpha(60);c.drawBitmap(frames.get(frame-1).layers.get(frames.get(frame-1).layers.size()-1).bitmap,0,0,bitmapPaint);}if(frame+1<frames.size()){bitmapPaint.setAlpha(45);c.drawBitmap(frames.get(frame+1).layers.get(frames.get(frame+1).layers.size()-1).bitmap,0,0,bitmapPaint);}bitmapPaint.setAlpha(255);}private void drawGrid(Canvas c){Paint p=new Paint(1);p.setColor(0x22334155);p.setStrokeWidth(1);int step=60;for(int x=0;x<projectW;x+=step)c.drawLine(x,0,x,projectH,p);for(int y=0;y<projectH;y+=step)c.drawLine(0,y,projectW,y,p);}
    private void drawRuler(Canvas c){Paint p=new Paint(1);p.setColor(0x5594A3B8);p.setStrokeWidth(2);if(ruler==RULER_STRAIGHT)c.drawLine(0,projectH*.5f,projectW,projectH*.5f,p);else if(ruler==RULER_PERSPECTIVE){float vx=projectW*.5f;for(int y=120;y<projectH;y+=100)c.drawLine(vx,projectH*.38f,0,y,p);for(int y=120;y<projectH;y+=100)c.drawLine(vx,projectH*.38f,projectW,y,p);}else if(ruler==RULER_RADIAL){float cx=projectW*.5f,cy=projectH*.5f;for(int a=0;a<360;a+=30){double q=Math.toRadians(a);c.drawLine(cx,cy,cx+(float)Math.cos(q)*projectW,cy+(float)Math.sin(q)*projectH,p);}}}
    private boolean inside(float x,float y){return canvasRect.contains(x,y);}private float cx(float x){return clamp((x-canvasRect.left)/scale,0,projectW-1);}private float cy(float y){return clamp((y-canvasRect.top)/scale,0,projectH-1);}private float clamp(float v,float a,float b){return Math.max(a,Math.min(b,v));}
    @Override public boolean onTouchEvent(MotionEvent e){if(playing||!inside(e.getX(),e.getY()))return true;ensure();float x=cx(e.getX()),y=cy(e.getY());LayerModel lm=frames.get(frame).layers.get(layer);if(lm.locked)return true;if(e.getActionMasked()==MotionEvent.ACTION_DOWN){sx=lx=x;sy=ly=y;moveStartX=x;moveStartY=y;if(tool==PICK){pick((int)x,(int)y);return true;}snapshot();if(tool==FILL)fill((int)x,(int)y);else if(tool==BRUSH||tool==ERASE)point(new Canvas(lm.bitmap),x,y);invalidate();return true;}if(e.getActionMasked()==MotionEvent.ACTION_MOVE){if(tool==BRUSH||tool==ERASE){stroke(new Canvas(lm.bitmap),lx,ly,x,y);lx=x;ly=y;invalidate();}else if(tool==MOVE){float dx=x-moveStartX,dy=y-moveStartY;translateBitmap(lm.bitmap,dx,dy);moveStartX=x;moveStartY=y;invalidate();}return true;}if(e.getActionMasked()==MotionEvent.ACTION_UP){if(tool==LINE||tool==RECT||tool==ELLIPSE)shape(new Canvas(lm.bitmap),sx,sy,x,y);invalidate();return true;}return true;}
    private void config(){paint.reset();paint.setAntiAlias(brush!=5);paint.setDither(true);paint.setStyle(Paint.Style.STROKE);paint.setStrokeCap(brush==5?Paint.Cap.SQUARE:Paint.Cap.ROUND);paint.setStrokeJoin(Paint.Join.ROUND);paint.setStrokeWidth(size);paint.clearShadowLayer();paint.setMaskFilter(null);if(tool==ERASE){paint.setColor(Color.TRANSPARENT);paint.setXfermode(new PorterDuffXfermode(PorterDuff.Mode.CLEAR));return;}int a=255;switch(brush){case 1:a=205;paint.setStrokeWidth(size*.78f);break;case 2:a=145;paint.setStrokeWidth(size*1.35f);break;case 3:a=75;paint.setStrokeWidth(size*2f);paint.setMaskFilter(new BlurMaskFilter(Math.max(1,size*.7f),BlurMaskFilter.Blur.NORMAL));break;case 4:a=220;paint.setMaskFilter(new BlurMaskFilter(Math.max(1,size*.22f),BlurMaskFilter.Blur.NORMAL));paint.setShadowLayer(size,0,0,brushColor);break;case 6:a=180;paint.setStrokeWidth(size*1.4f);break;case 7:a=230;paint.setStrokeWidth(size*1.8f);break;case 8:a=90;paint.setStrokeWidth(size*1.3f);break;case 9:a=230;paint.setStrokeWidth(size*.55f);break;case 10:a=245;paint.setStrokeWidth(size*.65f);break;case 11:a=230;paint.setShadowLayer(size,0,0,brushColor);break;}paint.setColor((brushColor&0x00ffffff)|(a<<24));paint.setXfermode(null);}
    private void point(Canvas c,float x,float y){config();float r=Math.max(.5f,size/2);if(brush==5)c.drawRect(x-r,y-r,x+r,y+r,paint);else c.drawCircle(x,y,r,paint);symPoint(c,x,y);}private void stroke(Canvas c,float x1,float y1,float x2,float y2){if(ruler==RULER_STRAIGHT&&Math.abs(x2-x1)>Math.abs(y2-y1))y2=y1;else if(ruler==RULER_STRAIGHT)x2=x1;config();c.drawLine(x1,y1,x2,y2,paint);symLine(c,x1,y1,x2,y2);}private void shape(Canvas c,float x1,float y1,float x2,float y2){config();RectF r=new RectF(Math.min(x1,x2),Math.min(y1,y2),Math.max(x1,x2),Math.max(y1,y2));if(tool==LINE)c.drawLine(x1,y1,x2,y2,paint);else if(tool==RECT)c.drawRect(r,paint);else c.drawOval(r,paint);symLine(c,x1,y1,x2,y2);}
    private void symPoint(Canvas c,float x,float y){float r=Math.max(.5f,size/2);if(symmetry==1||symmetry==3)c.drawCircle(projectW-x,y,r,paint);if(symmetry==2||symmetry==3)c.drawCircle(x,projectH-y,r,paint);if(symmetry==4)for(int a=90;a<360;a+=90){c.save();c.rotate(a,projectW/2f,projectH/2f);c.drawCircle(x,y,r,paint);c.restore();}}private void symLine(Canvas c,float a,float b,float x,float y){if(symmetry==1||symmetry==3)c.drawLine(projectW-a,b,projectW-x,y,paint);if(symmetry==2||symmetry==3)c.drawLine(a,projectH-b,x,projectH-y,paint);if(symmetry==3)c.drawLine(projectW-a,projectH-b,projectW-x,projectH-y,paint);if(symmetry==4)for(int q=90;q<360;q+=90){c.save();c.rotate(q,projectW/2f,projectH/2f);c.drawLine(a,b,x,y,paint);c.restore();}}
    private void pick(int x,int y){for(LayerModel l:frames.get(frame).layers)if(l.visible&&Color.alpha(l.bitmap.getPixel(x,y))>0){brushColor=l.bitmap.getPixel(x,y);tool=BRUSH;invalidate();return;}}
    private void fill(int sx,int sy){Bitmap b=frames.get(frame).layers.get(layer).bitmap;int[] p=new int[projectW*projectH];b.getPixels(p,0,projectW,0,0,projectW,projectH);int t=p[sy*projectW+sx];if(t==brushColor)return;int[] stack=new int[p.length];int top=0;stack[top++]=sy*projectW+sx;while(top>0){int i=stack[--top];if(p[i]!=t)continue;p[i]=brushColor;int x=i%projectW,y=i/projectW;if(x>0&&p[i-1]==t)stack[top++]=i-1;if(x+1<projectW&&p[i+1]==t)stack[top++]=i+1;if(y>0&&p[i-projectW]==t)stack[top++]=i-projectW;if(y+1<projectH&&p[i+projectW]==t)stack[top++]=i+projectW;if(top>stack.length-8)break;}b.setPixels(p,0,projectW,0,0,projectW,projectH);}
    private void translateBitmap(Bitmap b,float dx,float dy){Bitmap copy=b.copy(Bitmap.Config.ARGB_8888,true);Canvas c=new Canvas(b);c.drawColor(Color.TRANSPARENT,PorterDuff.Mode.CLEAR);c.drawBitmap(copy,dx,dy,bitmapPaint);recycle(copy);}
    public void addText(String text){ensure();LayerModel lm=frames.get(frame).layers.get(layer);if(lm.locked)return;Canvas c=new Canvas(lm.bitmap);Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);p.setColor(brushColor);p.setTextSize(56);p.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);c.drawText(text,(projectW-p.measureText(text))/2f,projectH/2f,p);invalidate();}
    public void addAsset(String assetName){ensure();LayerModel lm=frames.get(frame).layers.get(layer);if(lm.locked)return;Bitmap a=AssetLibrary.create(assetName,420,420);Canvas c=new Canvas(lm.bitmap);c.drawBitmap(a,(projectW-a.getWidth())/2f,(projectH-a.getHeight())/2f,bitmapPaint);recycle(a);invalidate();}
    public void addTexture(String textureName){ensure();LayerModel lm=frames.get(frame).layers.get(layer);if(lm.locked)return;Bitmap t=TextureFactory.create(textureName,projectW,projectH,0xFFF8FAFC,0x3347556B);new Canvas(lm.bitmap).drawBitmap(t,0,0,bitmapPaint);recycle(t);invalidate();}
    public void addImportedBitmap(Bitmap source){ensure();LayerModel lm=frames.get(frame).layers.get(layer);if(lm.locked||source==null)return;snapshot();Bitmap scaled=Bitmap.createScaledBitmap(source,Math.min(projectW,source.getWidth()),Math.min(projectH,source.getHeight()),true);new Canvas(lm.bitmap).drawBitmap(scaled,(projectW-scaled.getWidth())/2f,(projectH-scaled.getHeight())/2f,bitmapPaint);recycle(scaled);invalidate();}
    public void applyFilter(int type,float amount){LayerModel l=frames.get(frame).layers.get(layer);if(l.locked)return;snapshot();Bitmap out=ImageFilters.apply(l.bitmap,type,amount);recycle(l.bitmap);l.bitmap=out;invalidate();}
    public void rotateLayer90(){LayerModel l=frames.get(frame).layers.get(layer);if(l.locked)return;snapshot();Matrix m=new Matrix();m.postRotate(90,projectW/2f,projectH/2f);Bitmap out=Bitmap.createBitmap(l.bitmap,0,0,projectW,projectH,m,true);recycle(l.bitmap);l.bitmap=out;invalidate();}
    public void transformHorizontal(){transform(true,false);}public void transformVertical(){transform(false,true);}private void transform(boolean hx,boolean vy){LayerModel l=frames.get(frame).layers.get(layer);if(l.locked)return;snapshot();Matrix m=new Matrix();m.setScale(hx?-1:1,vy?-1:1,projectW/2f,projectH/2f);Bitmap x=Bitmap.createBitmap(l.bitmap,0,0,projectW,projectH,m,true);recycle(l.bitmap);l.bitmap=x;invalidate();}
    public Bitmap renderFrameBitmap(int index,boolean white){Bitmap b=blank();Canvas c=new Canvas(b);if(white)c.drawColor(Color.WHITE);if(index>=0&&index<frames.size())drawFrame(c,index,true);return b;}
    public void exportFrameSequence(){for(int i=0;i<frames.size();i++){Bitmap b=renderFrameBitmap(i,true);android.content.ContentValues v=new android.content.ContentValues();v.put(android.provider.MediaStore.Images.Media.DISPLAY_NAME,String.format(Locale.US,"%s_Frame_%03d.png",projectName.replaceAll("[^a-zA-Z0-9._-]+","_"),i+1));v.put(android.provider.MediaStore.Images.Media.MIME_TYPE,"image/png");v.put(android.provider.MediaStore.Images.Media.RELATIVE_PATH,android.os.Environment.DIRECTORY_PICTURES+"/DrawMotion/Frames");android.net.Uri u=getContext().getContentResolver().insert(android.provider.MediaStore.Images.Media.EXTERNAL_CONTENT_URI,v);try(java.io.OutputStream o=getContext().getContentResolver().openOutputStream(u)){if(o!=null)b.compress(Bitmap.CompressFormat.PNG,100,o);}catch(Exception ignored){}recycle(b);}toast("Frame sequence exported");}
    public void applyTemplate(String id){stopPlayback();clearAll();int count=1;if(id!=null&&!id.equals("blank"))count=id.equals("walk")||id.equals("run")?8:6;frames.clear();for(int i=0;i<count;i++){FrameModel f=new FrameModel();f.layers.add(new LayerModel("Background",solid(Color.WHITE)));f.layers.get(0).locked=true;LayerModel art=new LayerModel("Artwork",blank());Canvas c=new Canvas(art.bitmap);Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);float cx=projectW*(.25f+.5f*(i/(float)Math.max(1,count-1)));if("bounce".equals(id)){p.setColor(Color.rgb(124,58,237));c.drawCircle(cx,projectH*(.32f+.35f*(float)Math.sin(Math.PI*i/Math.max(1,count-1))),80,p);}else if("impact".equals(id)){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(18);p.setColor(Color.rgb(239,68,68));c.drawCircle(projectW*.5f,projectH*.5f,80+70*i,p);}else if("blink".equals(id)){p.setColor(Color.rgb(255,213,165));c.drawCircle(projectW*.5f,projectH*.45f,115,p);p.setColor(Color.DKGRAY);if(i<2||i>3){c.drawCircle(projectW*.46f,projectH*.44f,10,p);c.drawCircle(projectW*.54f,projectH*.44f,10,p);}}else if("spin".equals(id)){p.setColor(Color.rgb(34,211,238));c.save();c.rotate(i*45,projectW*.5f,projectH*.5f);c.drawRect(projectW*.43f,projectH*.28f,projectW*.57f,projectH*.72f,p);c.restore();}else if("pulse".equals(id)){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(22);p.setColor(Color.rgb(34,211,238));c.drawCircle(projectW*.5f,projectH*.5f,70+35*(i<=3?i:6-i),p);}else{p.setColor(Color.rgb(124,58,237));c.drawCircle(cx,projectH*.48f,60,p);p.setColor(Color.rgb(31,41,55));p.setStrokeWidth(16);c.drawLine(cx,projectH*.54f,cx,projectH*.72f,p);c.drawLine(cx,projectH*.72f,cx-55,projectH*.83f,p);c.drawLine(cx,projectH*.72f,cx+55,projectH*.83f,p);}f.layers.add(art);frames.add(f);}frame=0;layer=1;animation=count>1;invalidate();}
    public void renderFrame(Canvas c,int index){c.drawColor(Color.WHITE);if(index>=0&&index<frames.size())drawFrame(c,index,true);}public ArrayList<Bitmap> renderedFrames(){ArrayList<Bitmap> out=new ArrayList<>();for(int i=0;i<frames.size();i++){Bitmap b=blank();renderFrame(new Canvas(b),i);out.add(b);}return out;}public boolean exportProject(Context context,android.net.Uri uri){return ProjectIO.save(context,uri,frames,projectName,fps);}public boolean importProject(Context context,android.net.Uri uri){ProjectIO.Loaded p=ProjectIO.load(context,uri,projectW,projectH);if(p==null)return false;freeAll();frames.addAll(p.frames);projectName=p.name;fps=p.fps;frame=0;layer=1;animation=frames.size()>1;invalidate();return true;}public void startPlayback(){stopPlayback();playing=true;long d=1000L/Math.max(1,fps);playTask=new Runnable(){int i=0;public void run(){if(!playing)return;frame=i;invalidate();i=(i+1)%frames.size();postDelayed(this,d);}};post(playTask);}public void stopPlayback(){playing=false;if(playTask!=null)removeCallbacks(playTask);playTask=null;}public void clearAll(){freeAll();ensure();frame=0;layer=1;animation=false;clearHistory();invalidate();}private void freeFrame(FrameModel f){for(LayerModel l:f.layers)recycle(l.bitmap);f.layers.clear();}private void freeAll(){for(FrameModel f:frames)freeFrame(f);frames.clear();}private void toast(String x){Toast.makeText(getContext(),x,Toast.LENGTH_SHORT).show();}
}
