package com.nexauren.drawmotion;

import android.app.*;
import android.content.*;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.widget.*;
import java.io.InputStream;
import java.util.Locale;
import java.util.ArrayList;

public class MainActivity extends Activity {
 private static final int REQ_SAVE=10,REQ_OPEN=11,REQ_IMAGE=12,REQ_VIDEO=13;
 private LinearLayout root,timeline;private EditorCanvasView canvas;private boolean animation=false,grid=false;private int fps=12;private Button play;
 private final int BG=Color.WHITE,TEXT=Color.rgb(15,23,42),MUTED=Color.rgb(100,116,139),PURPLE=Color.rgb(124,58,237),CYAN=Color.rgb(8,145,178),CARD=Color.rgb(248,250,252),BORDER=Color.rgb(226,232,240);

 @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR);showHome();}
 private void showHome(){root=base();LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(20),dp(22),dp(20),dp(26));ScrollView s=new ScrollView(this);s.addView(c);
  TextView brand=t("DRAWMOTION",13,PURPLE,Typeface.BOLD);brand.setLetterSpacing(.18f);c.addView(brand);c.addView(t("2D Skill",38,TEXT,Typeface.BOLD),lp(-1,-2,0,4,0,1));c.addView(t("Draw • Animate • Build",18,CYAN,Typeface.BOLD),lp(-1,-2,0,0,0,22));
  c.addView(card("New Drawing","Illustration, concept art and game assets",v->openEditor(false,null)),lp(-1,-2,0,0,0,10));c.addView(card("New Animation","Frame-by-frame animation studio",v->openEditor(true,null)),lp(-1,-2,0,0,0,10));c.addView(card("Ready Projects","Characters, worlds, city scenes, vehicles and motion starters",v->readyProjects()),lp(-1,-2,0,0,0,10));c.addView(card("Materials & Objects","Brush textures, props, people, clothes, vehicles, worlds and backgrounds",v->assetHub()),lp(-1,-2,0,0,0,10));c.addView(card("Import .drawmotion","Continue any saved project",v->openProject()),lp(-1,-2,0,0,0,10));c.addView(card("Import Image","Use a photo or drawing as a layer",v->pickImage()),lp(-1,-2,0,0,0,12));
  TextView info=t("Native Android editor • real layers • advanced timeline • rulers • textures • assets • video export • no premium tier",14,MUTED,Typeface.NORMAL);info.setBackground(round(CARD,18));info.setPadding(dp(16),dp(16),dp(16),dp(16));c.addView(info);root.addView(s,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
 private LinearLayout base(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setBackgroundColor(BG);return x;}
 private View card(String a,String b,View.OnClickListener l){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(18),dp(17),dp(18),dp(17));x.setBackground(round(CARD,18));x.setOnClickListener(l);x.addView(t(a,19,TEXT,Typeface.BOLD));x.addView(t(b,14,MUTED,Typeface.NORMAL),lp(-1,-2,0,5,0,0));return x;}
 private void openEditor(boolean anim,String starter){animation=anim;root=base();LinearLayout top=row();Button back=btn("‹");back.setOnClickListener(v->{if(canvas!=null)canvas.stopPlayback();showHome();});top.addView(back,lp(dp(44),dp(44),3,0,3,0));TextView title=t(anim?"Animation Studio":"Illustration Studio",18,TEXT,Typeface.BOLD);top.addView(title,new LinearLayout.LayoutParams(0,dp(44),1));
  Button undo=btn("Undo");undo.setOnClickListener(v->canvas.undo());top.addView(undo,lp(-2,dp(44),2,0,2,0));Button redo=btn("Redo");redo.setOnClickListener(v->canvas.redo());top.addView(redo,lp(-2,dp(44),2,0,2,0));Button proj=btn("Project");proj.setOnClickListener(v->projectMenu());top.addView(proj,lp(-2,dp(44),2,0,2,0));Button exp=btn("Export");exp.setOnClickListener(v->exportMenu());top.addView(exp,lp(-2,dp(44),2,0,0,0));root.addView(top,new LinearLayout.LayoutParams(-1,dp(56)));
  canvas=new EditorCanvasView(this);canvas.setAnimationMode(anim);canvas.setFps(fps);canvas.setProjectName(starter==null?"Untitled":starter);root.addView(canvas,new LinearLayout.LayoutParams(-1,0,1));
  HorizontalScrollView toolScroll=new HorizontalScrollView(this);toolScroll.setHorizontalScrollBarEnabled(false);LinearLayout tools=new LinearLayout(this);tools.setPadding(dp(5),dp(5),dp(5),dp(5));
  for(String n:EditorCanvasView.BRUSHES){Button b=btn(n);b.setOnClickListener(v->selectTool(n));tools.addView(b,lp(dp(90),dp(40),2,0,2,0));}
  String[] shape={"Erase","Line","Rect","Circle","Fill","Pick","Move"};for(String n:shape){Button b=btn(n);b.setOnClickListener(v->selectTool(n));tools.addView(b,lp(dp(78),dp(40),2,0,2,0));}
  toolScroll.addView(tools);root.addView(toolScroll,new LinearLayout.LayoutParams(-1,dp(54)));
  HorizontalScrollView qv=new HorizontalScrollView(this);qv.setHorizontalScrollBarEnabled(false);LinearLayout quick=row();String[] q={"Color","Size","Ruler","Symmetry","Grid","Layers","Objects","Texture","Text","Image","Filters"};for(String n:q){Button b=btn(n);b.setOnClickListener(v->quick(n));quick.addView(b,lp(dp(78),dp(40),2,0,2,0));}qv.addView(quick);root.addView(qv,new LinearLayout.LayoutParams(-1,dp(54)));
  if(anim)buildTimeline();if(starter!=null)canvas.post(()->canvas.applyTemplate(starter));setContentView(root);
 }
 private void selectTool(String n){for(int i=0;i<EditorCanvasView.BRUSHES.length;i++)if(EditorCanvasView.BRUSHES[i].equals(n)){canvas.setBrushPreset(i);return;}if(n.equals("Erase"))canvas.setTool(EditorCanvasView.ERASE);else if(n.equals("Line"))canvas.setTool(EditorCanvasView.LINE);else if(n.equals("Rect"))canvas.setTool(EditorCanvasView.RECT);else if(n.equals("Circle"))canvas.setTool(EditorCanvasView.ELLIPSE);else if(n.equals("Fill"))canvas.setTool(EditorCanvasView.FILL);else if(n.equals("Pick"))canvas.setTool(EditorCanvasView.PICK);else if(n.equals("Move"))canvas.setTool(EditorCanvasView.MOVE);}
 private void quick(String n){switch(n){case "Color":colorDialog();break;case "Size":sizeDialog();break;case "Ruler":rulerDialog();break;case "Symmetry":symmetryDialog();break;case "Grid":grid=!grid;canvas.setGrid(grid);break;case "Layers":layersDialog();break;case "Objects":assetHub();break;case "Texture":textureDialog();break;case "Text":textDialog();break;case "Image":pickImage();break;case "Filters":filterDialog();break;}}
 private void buildTimeline(){LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setBackgroundColor(CARD);LinearLayout controls=row();Button add=btn("+ Frame");add.setOnClickListener(v->{canvas.addFrame();refreshTimeline();});controls.addView(add,equal());Button dup=btn("Duplicate");dup.setOnClickListener(v->{canvas.duplicateFrame();refreshTimeline();});controls.addView(dup,equal());Button del=btn("Delete");del.setOnClickListener(v->{canvas.deleteFrame();refreshTimeline();});controls.addView(del,equal());play=btn("Play ▶");play.setOnClickListener(v->{if(canvas.isPlaying()){canvas.stopPlayback();play.setText("Play ▶");}else{canvas.startPlayback();play.setText("Stop ■");}});controls.addView(play,equal());Button f=btn("FPS "+fps);f.setOnClickListener(v->fpsDialog(f));controls.addView(f,equal());p.addView(controls);HorizontalScrollView hs=new HorizontalScrollView(this);timeline=new LinearLayout(this);timeline.setPadding(dp(6),dp(3),dp(6),dp(5));hs.addView(timeline);p.addView(hs,new LinearLayout.LayoutParams(-1,dp(54)));TextView mode=t("Timeline • tap frames • layers are independent",12,MUTED,Typeface.NORMAL);mode.setPadding(dp(8),0,dp(8),dp(6));p.addView(mode);root.addView(p,new LinearLayout.LayoutParams(-1,dp(105)));refreshTimeline();}
 private void refreshTimeline(){if(timeline==null||canvas==null)return;timeline.removeAllViews();for(int i=0;i<canvas.getFrameCount();i++){final int k=i;TextView x=t(String.format(Locale.US,"%02d",i+1),12,i==canvas.getCurrentFrame()?Color.WHITE:MUTED,Typeface.BOLD);x.setGravity(Gravity.CENTER);x.setBackground(round(i==canvas.getCurrentFrame()?PURPLE:Color.WHITE,12));x.setOnClickListener(v->{canvas.selectFrame(k);refreshTimeline();});timeline.addView(x,lp(dp(48),dp(40),3,0,3,0));}}
 private void colorDialog(){int[] cs={Color.BLACK,Color.WHITE,Color.RED,Color.rgb(255,120,0),Color.YELLOW,Color.GREEN,Color.CYAN,Color.BLUE,PURPLE,Color.MAGENTA,Color.rgb(255,105,180)};LinearLayout g=new LinearLayout(this);g.setPadding(dp(12),dp(12),dp(12),dp(12));for(int c:cs){TextView s=t("",1,c,Typeface.NORMAL);s.setBackground(round(c,100));final int cc=c;s.setOnClickListener(v->canvas.setBrushColor(cc));g.addView(s,lp(dp(42),dp(42),4,4,4,4));}new AlertDialog.Builder(this).setTitle("Color palette").setView(g).setPositiveButton("Close",null).show();}
 private void sizeDialog(){SeekBar s=new SeekBar(this);s.setMax(119);s.setProgress(Math.max(0,(int)canvas.getBrushSize()-1));new AlertDialog.Builder(this).setTitle("Brush size").setMessage("1–120 px").setView(s).setPositiveButton("Apply",(d,w)->canvas.setBrushSize(s.getProgress()+1)).show();}
 private void rulerDialog(){new AlertDialog.Builder(this).setTitle("Ruler").setItems(EditorCanvasView.RULERS,(d,w)->canvas.setRuler(w)).show();}
 private void symmetryDialog(){String[] x={"Off","Vertical","Horizontal","Mirror","Radial 4×"};new AlertDialog.Builder(this).setTitle("Symmetry").setItems(x,(d,w)->canvas.setSymmetry(w)).show();}
 private void fpsDialog(Button b){SeekBar s=new SeekBar(this);s.setMax(29);s.setProgress(fps-1);new AlertDialog.Builder(this).setTitle("Animation FPS").setMessage("1–30 FPS").setView(s).setPositiveButton("Apply",(d,w)->{fps=s.getProgress()+1;canvas.setFps(fps);b.setText("FPS "+fps);}).show();}
 private void layersDialog(){new AlertDialog.Builder(this).setTitle("Layers • "+canvas.currentLayerName()+" • "+canvas.currentBlend()).setItems(canvas.layerNames(),(d,w)->{canvas.selectLayer(w);layersActions();}).setPositiveButton("Add",(d,w)->{canvas.addLayer();layersDialog();}).setNegativeButton("Done",null).show();}
 private void layersActions(){String[] a={"Duplicate","Delete","Move Up","Move Down","Hide/Show","Blend Mode","Opacity","Flip Horizontal","Flip Vertical","Rotate 90°"};new AlertDialog.Builder(this).setTitle(canvas.currentLayerName()).setItems(a,(d,w)->{if(w==0)canvas.duplicateLayer();else if(w==1)canvas.deleteLayer();else if(w==2)canvas.moveLayerUp();else if(w==3)canvas.moveLayerDown();else if(w==4)canvas.toggleLayer();else if(w==5)canvas.cycleBlend();else if(w==6)opacityDialog();else if(w==7)canvas.transformHorizontal();else if(w==8)canvas.transformVertical();else canvas.rotateLayer90();}).show();}
 private void opacityDialog(){SeekBar s=new SeekBar(this);s.setMax(255);s.setProgress(255);new AlertDialog.Builder(this).setTitle("Layer opacity").setView(s).setPositiveButton("Apply",(d,w)->canvas.setLayerOpacity(s.getProgress())).show();}
 private void textDialog(){EditText e=new EditText(this);e.setHint("Type text");new AlertDialog.Builder(this).setTitle("Text").setView(e).setPositiveButton("Add",(d,w)->{String x=e.getText().toString().trim();if(!x.isEmpty())canvas.addText(x);}).setNegativeButton("Cancel",null).show();}
 private void filterDialog(){String[] x={"Brightness +","Brightness -","Contrast +","Grayscale","Invert","Sepia"};new AlertDialog.Builder(this).setTitle("Filters").setItems(x,(d,w)->{if(w==0)canvas.applyFilter(0,35);else if(w==1)canvas.applyFilter(0,-35);else if(w==2)canvas.applyFilter(1,55);else if(w==3)canvas.applyFilter(2,0);else if(w==4)canvas.applyFilter(3,0);else canvas.applyFilter(4,0);}).show();}
 private void textureDialog(){new AlertDialog.Builder(this).setTitle("Textures & patterns").setItems(TextureFactory.NAMES,(d,w)->canvas.addTexture(TextureFactory.NAMES[w])).show();}
 private void assetHub(){new AlertDialog.Builder(this).setTitle("Materials & Objects").setItems(AssetLibrary.CATEGORIES,(d,w)->assetCategory(AssetLibrary.CATEGORIES[w])).show();}
 private void assetCategory(String cat){String[] ns=AssetLibrary.names(cat);new AlertDialog.Builder(this).setTitle(cat).setItems(ns,(d,w)->canvas.addAsset(ns[w])).show();}
 private void readyProjects(){String[] names={"Bouncing Ball","Blink","Impact","Spin Loop","Pulse","Walk Cycle","Jump","Wave","Run Cycle","Blank Canvas"};String[] ids={"bounce","blink","impact","spin","pulse","walk","jump","wave","run","blank"};new AlertDialog.Builder(this).setTitle("Ready animation projects").setItems(names,(d,w)->openEditor(true,ids[w])).show();}
 private void projectMenu(){String[] x={"Rename Project","Save .drawmotion","Open .drawmotion","Add Layer","Layers Panel"};new AlertDialog.Builder(this).setTitle("Project").setItems(x,(d,w)->{if(w==0)renameProject();else if(w==1)saveProject();else if(w==2)openProject();else if(w==3)canvas.addLayer();else layersDialog();}).show();}
 private void renameProject(){EditText e=new EditText(this);e.setText(canvas.getProjectName());new AlertDialog.Builder(this).setTitle("Project name").setView(e).setPositiveButton("Save",(d,w)->canvas.setProjectName(e.getText().toString())).setNegativeButton("Cancel",null).show();}
 private void saveProject(){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/octet-stream");i.putExtra(Intent.EXTRA_TITLE,safe(canvas.getProjectName())+".drawmotion");startActivityForResult(i,REQ_SAVE);}
 private void openProject(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/octet-stream");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,REQ_OPEN);}
 private void exportMenu(){String[] x={"PNG on white","Transparent PNG","Sprite sheet","Frame sequence","MP4 video"};new AlertDialog.Builder(this).setTitle("Export").setItems(x,(d,w)->{if(w==0)exportPng(false);else if(w==1)exportPng(true);else if(w==2)exportSprite();else if(w==3)canvas.exportFrameSequence();else exportVideo();}).show();}
 private void exportPng(boolean transparent){Bitmap b=canvas.renderFrameBitmap(canvas.getCurrentFrame(),!transparent);android.content.ContentValues v=new android.content.ContentValues();v.put(android.provider.MediaStore.Images.Media.DISPLAY_NAME,safe(canvas.getProjectName())+"_"+System.currentTimeMillis()+".png");v.put(android.provider.MediaStore.Images.Media.MIME_TYPE,"image/png");v.put(android.provider.MediaStore.Images.Media.RELATIVE_PATH,android.os.Environment.DIRECTORY_PICTURES+"/DrawMotion");Uri u=getContentResolver().insert(android.provider.MediaStore.Images.Media.EXTERNAL_CONTENT_URI,v);try(java.io.OutputStream o=getContentResolver().openOutputStream(u)){if(o!=null)b.compress(Bitmap.CompressFormat.PNG,100,o);Toast.makeText(this,transparent?"Transparent PNG exported":"PNG exported",Toast.LENGTH_SHORT).show();}catch(Exception e){Toast.makeText(this,"Export failed",Toast.LENGTH_SHORT).show();}b.recycle();}
 private void exportSprite(){ArrayList<Bitmap> fs=canvas.renderedFrames();if(fs.isEmpty())return;int n=fs.size(),cols=Math.min(4,n),rows=(int)Math.ceil(n/(double)cols),w=fs.get(0).getWidth(),h=fs.get(0).getHeight();Bitmap sheet=Bitmap.createBitmap(w*cols,h*rows,Bitmap.Config.ARGB_8888);android.graphics.Canvas c=new android.graphics.Canvas(sheet);c.drawColor(Color.WHITE);for(int i=0;i<n;i++)c.drawBitmap(fs.get(i),(i%cols)*w,(i/cols)*h,null);for(Bitmap b:fs)b.recycle();android.content.ContentValues v=new android.content.ContentValues();v.put(android.provider.MediaStore.Images.Media.DISPLAY_NAME,safe(canvas.getProjectName())+"_sprites.png");v.put(android.provider.MediaStore.Images.Media.MIME_TYPE,"image/png");v.put(android.provider.MediaStore.Images.Media.RELATIVE_PATH,android.os.Environment.DIRECTORY_PICTURES+"/DrawMotion");Uri u=getContentResolver().insert(android.provider.MediaStore.Images.Media.EXTERNAL_CONTENT_URI,v);try(java.io.OutputStream o=getContentResolver().openOutputStream(u)){if(o!=null)sheet.compress(Bitmap.CompressFormat.PNG,100,o);Toast.makeText(this,"Sprite sheet exported",Toast.LENGTH_SHORT).show();}catch(Exception e){Toast.makeText(this,"Export failed",Toast.LENGTH_SHORT).show();}sheet.recycle();}
 private void exportVideo(){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("video/mp4");i.putExtra(Intent.EXTRA_TITLE,safe(canvas.getProjectName())+".mp4");startActivityForResult(i,REQ_VIDEO);}
 private void pickImage(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,REQ_IMAGE);}
 @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(result!=RESULT_OK||data==null||data.getData()==null)return;Uri u=data.getData();if(req==REQ_SAVE&&canvas!=null){canvas.exportProject(this,u);return;}if(req==REQ_OPEN){if(canvas==null)openEditor(false,null);if(canvas.importProject(this,u)){animation=canvas.isAnimationMode();if(animation&&timeline==null)buildTimeline();}return;}if(req==REQ_IMAGE&&canvas!=null){try(InputStream in=getContentResolver().openInputStream(u)){Bitmap b=BitmapFactory.decodeStream(in);canvas.addImportedBitmap(b);}catch(Exception e){Toast.makeText(this,"Image import failed",Toast.LENGTH_SHORT).show();}return;}if(req==REQ_VIDEO&&canvas!=null){final Uri out=u;new Thread(()->{ArrayList<Bitmap> fs=canvas.renderedFrames();boolean ok=VideoExporter.export(this,out,fs,fps);for(Bitmap b:fs)if(b!=null&&!b.isRecycled())b.recycle();runOnUiThread(()->Toast.makeText(this,ok?"MP4 exported":"Video export failed",Toast.LENGTH_SHORT).show());}).start();}}
 private Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextColor(TEXT);b.setTextSize(11);b.setAllCaps(false);b.setPadding(dp(4),0,dp(4),0);b.setBackground(round(Color.WHITE,12));return b;}private LinearLayout row(){LinearLayout x=new LinearLayout(this);x.setGravity(Gravity.CENTER_VERTICAL);x.setPadding(dp(5),dp(5),dp(5),dp(5));return x;}private LinearLayout.LayoutParams equal(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(40),1);p.setMargins(dp(2),0,dp(2),0);return p;}private TextView t(String s,float z,int c,int style){TextView x=new TextView(this);x.setText(s);x.setTextSize(z);x.setTextColor(c);x.setTypeface(Typeface.create(Typeface.DEFAULT,style));return x;}private GradientDrawable round(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));g.setStroke(dp(1),BORDER);return g;}private LinearLayout.LayoutParams lp(int w,int h,int l,int tt,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(w,h);p.setMargins(dp(l),dp(tt),dp(r),dp(b));return p;}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}private String safe(String s){String x=s==null?"DrawMotion":s.replaceAll("[^a-zA-Z0-9._-]+","_");return x.isEmpty()?"DrawMotion":x;}
}